export const ERROR_CODES = {
  GENERIC_ERROR: "GENERIC_ERROR",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  RECIPIENT_NOT_FOUND: "RECIPIENT_NOT_FOUND",
  NETWORK_ERROR: "NETWORK_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  NO_SECURITY_ENABLED: "NO_SECURITY_ENABLED",
} as const;
